### ISSUE TITLE
errors go to stdout

### ISSUE THREAD

**Issue by barryrowlingson** [sodastsai/taskr#2]
`task` sends error message to the standard output stream, not the standard error stream, so errors can go unnoticed and end up in the output. Example, using the python example in the docs:

Correct usage:
```
$ ./mytask.py run -s 999 this that
Run from this to that by speed=999
```

incorrect usage, shows error message:

```
$ ./mytask.py run -s 999
mytask.py run: error: the following arguments are required: source, destination

usage: mytask.py run [-h] [-s SPEED] source destination
```

but if I redirect the output, I don't see the error - it goes into the file:

```
$ ./mytask.py run -s 999 > test.out
```

this is unlike most unix commands where the error goes to stderr and is seen even when the output is redirected:

```
$ tar --goop >test.out
tar: unrecognised option '--goop'
Try 'tar --help' or 'tar --usage' for more information.
```

 I note this project has not been updated for a while, so if there is an alternative command-line utility for python that you recommend, delete this issue and let me know!

**Comment by sodastsai** [comment]
Hi Barry

Sorry for this very late response to your issue. And yes as you mentioned in the end of the issue, this project is not maintained for a long while after I switched my job and didn't use Python as my daily coding language. 

In terms of alternate, hope I can still help on this, I would recommend "click" - https://click.palletsprojects.com/en/7.x/index.html

Cheers and stay safe :)
